### ISSUE TITLE
Not working.....

### ISSUE THREAD

**Issue by chriswalkerx** [spencerjpotts/Ark-FisherMan#8]
I've followed the video, I've followed the instructions. I've done everything in my settings and for the life of me cannot get this to work. The script is working if i open notepad and it starts typing away. But will not for the life of me auto catch these fish. It doesnt even auto snap the line. It just sits there dormant...

**Comment by Nackenschelle** [comment]
script dont work after new update

**Comment by chriswalkerx** [comment]
understandable, but this was before this mornings update. Will standby till it is updated

**Comment by spencerjpotts** [comment]
@Nackenschelle script isn't working atm? I'll log now and check it out

**Comment by spencerjpotts** [comment]
@chriswalkerx ill get back to you when i find something, sorry dude!

**Comment by spencerjpotts** [comment]
@chriswalkerx @Nackenschelle The script is working fine for me, it must be a config issue on your ends, I'll do some recon and find out the specific configs

**Comment by Nackenschelle** [comment]
i checked few min ago it fails on the first button.

**Comment by Nackenschelle** [comment]
there are some small updates did they changed anything

**Comment by spencerjpotts** [comment]
@Nackenschelle Not that I could see, and it still functions for me fine.. :( still looking though :)

**Comment by chriswalkerx** [comment]
what can you do as far as get it working for me? i copied your config and everything and nothing....

**Comment by chriswalkerx** [comment]
.........?

**Comment by spencerjpotts** [comment]
Have you tried setting game settings to default?

**Comment by chriswalkerx** [comment]
yes, every single thing you recommend. If youd like we can exchange steam usernames and you can give it a try? Or come to our server?

**Comment by spencerjpotts** [comment]
@chriswalkerx yeah sounds good, http://steamcommunity.com/profiles/76561198032748139/

**Comment by chriswalkerx** [comment]
it still isnt working for me so why is this closed?

**Comment by spencerjpotts** [comment]
Stay active and communicate, I posted my steam info up though you didn't add me within a few days so I removed the comment. What you have issued is "The script is working if i open notepad and it starts typing away. But will not for the life of me auto catch these fish. It doesnt even auto snap the line. It just sits there dormant" we know ahk is working because the script works on text editor, so it's not ahk, if it doesn't auto snap it means it's detecting nothing, so its not even clicking the characters to cause snaps, this sounds like a resolution issue, could you please send me your settings?
