### ISSUE TITLE
NOT WORKING - FOUND possible fix?

### ISSUE THREAD

**Issue by Justwurst** [spencerjpotts/Ark-FisherMan#9]
Hey, first i just want to give you a huge thank you for your great work on it. For me it Works just fine BUT there is a few "issues" that seem to occur that i had to fix. 
1. You have to be in windowed mode
2. you have to disc. all your extra monitors (i use 3 but it works only if i have 1 connected)
2. it seems like disabling game HUD provides the script a better performance ?

PS: is there any way to support you with a small donation ? i wanna kepp your motivation high to provide a nicely working fishing bot/script! im new to GitHub so i dont really know how to communicate over here

**Comment by spencerjpotts** [comment]
Hey @Justwurst thanks for the support and kind words, support me in what way you feel is best, I don't mind, iv added some info for supporting me in the README.md.

I'm going to have to log on tonight and check 1, 3 out just to make sure, because I do run the script on WindowedFullscreen and I have multiple monitors, 1920x1080p running fine, I have a feeling that my Geforce Experience is stuffing things up so the end result is buggy and working for some and not others. 

with multiple monitors ensure that you have the active screen active, the code has no reactivate screen function so if you have a cursor on another active screen it me not find it and not work, or just spamming random qweasdzxc to desktop haha

 I'l be doing some code changes in the next few days as well, keep me posted and ill do the same thanks for the support once again 👍
